apiVersion: apps/v1
kind: Deployment
metadata:
   name: EKSDeploy
   labels:
     app: eks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-deployment
  template:
    metadata:
      labels:
        app: eks-deployment
    spec:
      containers:
      - name: ecs-container
        image: 408935668637.dkr.ecr.us-east-1.amazonaws.com/ecs-container
        imagePullPolicy: Always
        ports:
        - containerPort: 8080